# Generated by Django 4.2.7 on 2025-11-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Free Fire, PUBG Mobile', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='gamepad', help_text='FontAwesome icon name (e.g., fire, crosshairs)', max_length=50)),
                ('banner_color', models.CharField(default='#2c3e6d', help_text='Hex color for banner', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('product_types', models.TextField(help_text='Comma-separated list (e.g., DIAMONDS, MEMBERSHIP, UC)')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_items/'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.game'),
        ),
    ]
