# Generated by Django 4.2.7 on 2025-11-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_remove_storeitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Game icon/logo image', null=True, upload_to='games/'),
        ),
    ]
