# Generated by Django 4.2.7 on 2025-11-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='e.g., 100 diamonds, 60 UC'),
        ),
    ]
