# Generated by Django 4.2.7 on 2025-11-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tournament_creator_tournament_room_id_set_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_claim', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose')], max_length=10)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='tournament_results/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
