# Generated by Django 4.2.7 on 2025-11-03 11:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_first_result_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchroom_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('game', models.CharField(choices=[('freefire', 'Free Fire'), ('pubg', 'PUBG Mobile')], max_length=20)),
                ('team_type', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad')], default='squad', max_length=20)),
                ('max_players', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('entry_fee', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('game_time', models.DateTimeField()),
                ('game_map', models.CharField(max_length=100)),
                ('first_place_prize', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rank_2_5_prize', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('per_kill_prize', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('rules_regulations', models.TextField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.CharField(blank=True, max_length=50)),
                ('room_password', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_full_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-game_time'],
            },
        ),
        migrations.CreateModel(
            name='FullTournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_tag', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('prize_won', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_participants', to='core.fulltournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-kills'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
